sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: miku3939
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDan8tTwYbn7CEW4PTo
    access-key-secret: 7HIo7biW7hDOn7qad1kjXtJdSvWXkC
    bucket-name: aiyi-take-out
  redis:
    host: localhost
    port: 6379
    password: miku3939
    database: 1
